<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('User', 'doctrine');

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userid
 * @property string $login
 * @property string $password
 * 
 * @method integer getUserid()   Returns the current record's "userid" value
 * @method string  getLogin()    Returns the current record's "login" value
 * @method string  getPassword() Returns the current record's "password" value
 * @method User    setUserid()   Sets the current record's "userid" value
 * @method User    setLogin()    Sets the current record's "login" value
 * @method User    setPassword() Sets the current record's "password" value
 * 
 * @package    shzambles-nbsf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shzambles.sUser');
        $this->hasColumn('userid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'shzambles."sUser_userId_seq"',
             'length' => 4,
             ));
        $this->hasColumn('login', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('password', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}